import { FieldConfig } from '../types';

export const FIELD_CATEGORIES = [
  { id: 'basico', label: 'Dados Básicos', icon: 'Building' },
  { id: 'localizacao', label: 'Localização', icon: 'MapPin' },
  { id: 'atividades', label: 'Serviços & Produtos', icon: 'Sparkles' },
  { id: 'contato', label: 'Canais de Contato', icon: 'Phone' },
  { id: 'redes', label: 'Redes Sociais', icon: 'Share2' },
  { id: 'operacao', label: 'Funcionamento', icon: 'Clock' },
] as const;

export const GMN_FIELDS: FieldConfig[] = [
  {
    key: 'nomeEmpresa',
    label: 'Nome da Empresa',
    placeholder: 'Ex: Start Mkt Digital MS',
    type: 'text',
    category: 'basico',
    helpText: 'O nome oficial da sua empresa conforme aparece na fachada ou registros.',
  },
  {
    key: 'descricao',
    label: 'Descrição',
    placeholder: 'Ex: Agência de marketing digital especializada em SEO, tráfego pago...',
    type: 'textarea',
    category: 'basico',
    helpText: 'Resumo de até 750 caracteres sobre quem vocês são e o que fazem.',
  },
  {
    key: 'endereco',
    label: 'Endereço',
    placeholder: 'Rua, Número, Bairro, Cidade e Estado',
    type: 'text',
    category: 'localizacao',
    helpText: 'Endereço físico completo caso receba clientes. Deixe vazio se for apenas online.',
  },
  {
    key: 'cep',
    label: 'CEP',
    placeholder: 'Ex: 79002-000',
    type: 'text',
    category: 'localizacao',
    helpText: 'Código de Endereçamento Postal que ajuda o Google a fixar seu alfinete no mapa.',
  },
  {
    key: 'areaCobertura',
    label: 'Área de Cobrança / Cobertura',
    placeholder: 'Ex: Campo Grande, Dourados, Terenos...',
    type: 'text',
    category: 'localizacao',
    helpText: 'Regiões que sua empresa atende em domicílio ou entrega (se aplicável).',
  },
  {
    key: 'dataAbertura',
    label: 'Data de Abertura',
    placeholder: 'Selecione a data de inauguração',
    type: 'date',
    category: 'basico',
    helpText: 'Data em que o negócio abriu ou planeja abrir. Ajuda na autoridade do perfil.',
  },
  {
    key: 'servicos',
    label: 'Serviços',
    placeholder: 'Ex: Desenvolvimento web, Gestão de Redes Sociais, Branding...',
    type: 'textarea',
    category: 'atividades',
    helpText: 'Adicione termos claros para seus serviços, pois isso ajuda muito nas buscas.',
  },
  {
    key: 'produtos',
    label: 'Produtos',
    placeholder: 'Ex: Consultorias de SEO, Mentorias Digitais, Cursos online...',
    type: 'textarea',
    category: 'atividades',
    helpText: 'Principais itens físicos ou virtuais oferecidos pela marca.',
  },
  {
    key: 'site',
    label: 'Site',
    placeholder: 'Ex: https://www.startmktdigital.com.br',
    type: 'url',
    category: 'contato',
    helpText: 'O link principal do seu portal, portfólio ou landing page.',
  },
  {
    key: 'whatsapp',
    label: 'WhatsApp',
    placeholder: 'Ex: (67) 99317-4612',
    type: 'tel',
    category: 'contato',
    helpText: 'Celular principal com DDD configurado para atendimento comercial rápido.',
  },
  {
    key: 'facebook',
    label: 'Facebook',
    placeholder: 'Ex: https://facebook.com/suapagina',
    type: 'url',
    category: 'redes',
    helpText: 'URL completa do perfil ou página do Facebook.',
  },
  {
    key: 'instagram',
    label: 'Instagram',
    placeholder: 'Ex: https://instagram.com/seuusuario',
    type: 'url',
    category: 'redes',
    helpText: 'URL completa ou @usuario do seu perfil do Instagram.',
  },
  {
    key: 'linkedin',
    label: 'LinkedIn',
    placeholder: 'Ex: https://linkedin.com/company/suaempresa',
    type: 'url',
    category: 'redes',
    helpText: 'URL do perfil profissional ou página corporativa.',
  },
  {
    key: 'tiktok',
    label: 'TikTok',
    placeholder: 'Ex: https://tiktok.com/@seuusuario',
    type: 'url',
    category: 'redes',
    helpText: 'URL do canal no TikTok, se aplicável.',
  },
  {
    key: 'horario',
    label: 'Horário de Funcionamento (Semana)',
    placeholder: 'Ex: Segunda a Sexta das 08:30 às 18:00',
    type: 'text',
    category: 'operacao',
    helpText: 'Horários regulados de Segunda a Sexta.',
  },
  {
    key: 'horarioSabado',
    label: 'Horário Sábado',
    placeholder: 'Ex: Sábado das 09:00 às 12:00',
    type: 'text',
    category: 'operacao',
    helpText: 'Horário de atividade no Sábado. Caso fechado, indique "Fechado".',
  },
  {
    key: 'observacoes',
    label: 'Observações Gerais',
    placeholder: 'Ex: Estacionamento próprio, Acessibilidade para cadeirantes...',
    type: 'textarea',
    category: 'operacao',
    helpText: 'Qualquer atributo especial, feriados ou observações adicionais úteis.',
  },
];
